import type { Metadata } from "next"
import "./globals.css"
import { Providers } from "./providers"
import { Toaster } from 'sonner';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <div>
        <Providers>
           <Toaster richColors position="top-right" />
          {children}
        </Providers>
        </div>
      </body>
    </html>
  )
}
